"""Add SiteConfig model

Revision ID: 12cbe8f6d4f1
Revises: a3af967bbf2d
Create Date: 2026-06-19 11:12:40.533715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cbe8f6d4f1'
down_revision = 'a3af967bbf2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_config'))
    )
    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_config_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_config_key'))

    op.drop_table('site_config')
    # ### end Alembic commands ###
